name: Pipeline CI/CD - Paciente

on:
  push:
    branches:
      - master
      - deploy

jobs:
  config-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

  build-app:
    needs: config-env
    runs-on: ubuntu-latest
    steps:
      - name: Build do JAR do projeto
        run: |
          echo "Buildando o JAR..."
          mvn clean package
          echo "Build concluído com sucesso!"

  deploy-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Faz o Deploy para VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH }}
          port: ${{ secrets.VPS_PORT }}
          source: "target/consultorio-ms-medico.jar"
          target: "/app"
          strip_components: 1